### PR TITLE
Use single line description in project docstring

### LINKED ISSUE #10: pyproject description updates
Still trying to figure out how everything works and fits together, but here is what I have found so far. This was originally triggered by looking into https://github.com/arviz-devs/xarray-einstats/issues/18, but it is not necessarily related, to try and fix this I ended up doing some workarounds that are far from ideal but ti seems they will be necessary for the time being.

The pyproject.toml template currently lists two dynamic fields:

https://github.com/astrojuanlu/cookiecutter-pylib/blob/3a7b112deedbac9028ff36765f4e70f9424cb7b5/%7B%7Bcookiecutter.project_name%7D%7D/pyproject.toml#L24

From what I understood, this means that they are not defined in the pyproject file itself but should instead be retrieved dynamically by the build library during the install process. flit seems to then magically take the correct version for the package and a short description. The version thing works great, but the short description does not. What ends up being used as short description is the first line of the `__init__.py` package level docstring:

https://github.com/astrojuanlu/cookiecutter-pylib/blob/3a7b112deedbac9028ff36765f4e70f9424cb7b5/%7B%7Bcookiecutter.project_name%7D%7D/src/%7B%7Bcookiecutter.package_name%7D%7D/__init__.py#L1-L5

that means that with the current config, the package name is repeated as short description instead of using the actual short description. This can be seen in https://pypi.org/project/xarray-einstats/ for example:

image

`xarray-einstats.` is used as short description (side note, since pydocstyle was added to tox checks, I think line two needs to end with a dot for a clean generated project to pass the checks). This can be fixed by updating the docstring template in init.py or by making the description be a static field, I am not sure it is worth it to have `description` as a dynamic field using the first line of the dosctring as it is still hardcoded in the readme.

I can submit a PR for either of the two options. Let me know which one do you prefer or if you think a 3rd option would be better.

### PR DESCRIPTION
**Pull request by OriolAbril**
This fixes the issue of flit not retrieving the correct short description for the project. Closes #10

### CODE REVIEW

**Review by astrojuanlu — APPROVED** [review]
Thanks a lot!

**Comment by astrojuanlu** [comment]
Hmm tests have just failed? On mobile, will have a look later

**Comment by astrojuanlu** [comment]
Makes sense because apparently tests don't run for PRs 🤔

**Comment by OriolAbril** [comment]
Trying to fix it

**Pull request merged**
